# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Jekyll

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    path:
    output: true
    filter: strict

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  &#39;0&#39;: u
  &#39;1&#39;: p
  &#39;2&#39;: l
  &#39;3&#39;: o
  &#39;4&#39;: a
  &#39;5&#39;: d
  &#39;6&#39;: s
  data: _data
  includes: _includes
  layouts: _layouts
  static:
  uploads: uploads
  dam_uploads:
  dam_static:
  collections:

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
